################################# Default configuration ###################
baseURL = "https://jwarner112.github.io/metamesh.org"
title = "Meta Mesh Wireless Communities [Staging]"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# # disqus short name
# disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ['fr']


############################# Plugins ##########################
# Fonts -- Anaheim, Quattrocento Sans => https://fonts.google.com/?selection.family=Anaheim|Quattrocento+Sans:wght@400;700
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# jQuery 3.5.1 => https://jquery.com
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"

# Lozad -- lazy loader => https://apoorv.pro/lozad.js
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/lozad.js/1.15.0/lozad.min.js"

# Magnific Popup 1.1.0 -- jQuery plugin => https://dimsemenov.com/plugins/magnific-popup
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"

# Shuffle -- sorting/filtering helper => https://github.com/Vestride/Shuffle
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/Shuffle/5.2.3/shuffle.min.js"

# Slick 1.8.1 -- carousel => https://github.com/kenwheeler/slick.git
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"

# Twitter Bootstrap 4.5.0 => https://getbootstrap.com/
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"


# TODO: Replace with external embed
[[params.plugins.js]]
link = "plugins/google-map/map.js"

# TODO: Replace with another icon library, maybe https://thenounproject.com?
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"




############################# Navigation ##################################
[[menu.main]]
name = "about"
URL = "about"
weight = 1

[[menu.main]]
name = "services"
URL = "services"
weight = 2

[[menu.main]]
name = "portfolio"
URL = "portfolio"
weight = 3

[[menu.main]]
name = "team"
URL = "team"
weight = 4

[[menu.main]]
name = "pricing"
URL = "pricing"
weight = 5

[[menu.main]]
name = "blog"
URL = "blog"
weight = 6

[[menu.main]]
name = "contact"
URL = "contact"
weight = 7


#### external / static link ####
[[menu.static]]
name = "github"
URL = "https://github.com/metamesh"
weight = 8


############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Responsive Multipurpose Parallax HTML5 Template"
author = "Meta Mesh Wireless Communities"
# Google Analytics
google_analytics_id = "UA-35167230-1"
# post share
post_share = true

# preloader
[params.preloader]
enable = true
preloader = "images/logo.png"

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=long-secret-token"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"


############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/MetaMesh/"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "http://www.twitter.com/metameshwc"

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "https://www.youtube.com/metameshwc"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/meta-mesh-llc"

# [[params.social]]
# icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
# link = "#"

# [[params.social]]
# icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
# link = "#"



################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "copyright &copy; 2020 Meta Mesh Wireless Communities, all rights reserved"


# ################################ France Language ########################
# [Languages.fr]
# languageName = "Fr"
# languageCode = "fr-fr"
# contentDir = "content/french"
# weight = 2
# home = "Accueil"
# copyright = "copyright &copy; 2020 [gethugothemes](https://gethugothemes.com) tous droits réservés"
