---
new_page_extension: md
auto_deploy: false
admin_path: ".forestry"
webhook_url: 
sections:
- type: heading
  label: Edit Content
- type: directory
  path: data/en
  label: Site Data
  create: all
  match: "**/*.{yml,yaml,json,toml}"
  new_doc_ext: yml
  templates:
  - banner
  - team-member
- type: document
  path: data/en/banner.yml
  label: Banner
  match: "**/*"
- type: directory
  path: data/en/team
  label: Team Members
  create: documents
  match: "**/*.{yml,yaml,json,toml}"
  new_doc_ext: yml
  templates:
  - team-member
upload_dir: assets/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.71.1
