---
new_page_extension: md
auto_deploy: false
admin_path: ".forestry"
webhook_url: 
sections:
- type: heading
  label: Create New
- type: directory
  path: content/english/author
  label: Authors
  create: documents
  match: "*.md"
  templates:
  - author
- type: directory
  path: content/english/blog
  label: Blog Post
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: content/english/xyzzy
  label: xyzzy's
  create: all
  match: "**/*.md"
  templates:
  - xyzzy
- type: heading
  label: Edit Content
- type: document
  path: data/en/front_page.yml
  label: Front Page
upload_dir: assets/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.71.1
